version: '3.8'

services:
  db_users:
    build:
      context: ./backend/users
      dockerfile: dockerfile.db
    container_name: db_users
    # Add any other configurations for the consumer service if needed

  app_users:
    build:
      context: ./backend/users
      dockerfile: dockerfile.app
    container_name: app_users
    ports:
      - "8080:8080"
    depends_on:
      - db_users

